mysql:
  host: db
  port: 3306
  user: root
  password: mx/58MFuLJ6^%.q
  db: greenhouse
  charset: utf8

app:
  host: 0.0.0.0
  port: 9000
  jwt_secret_key: 'greenhouse'
  black_list_enabled: true
  black_list_checks:
    - refresh

mqtt:
  broker_url: emqx
  port: 8083
  user: emqx
  pwd: public
  transport: websockets
  client_id: server-mqtt
  http_api_port: 8081
  basic_auth_username: admin
  basic_auth_password: public

redis:
  url: redis://:7GhVu9i24mjK@redis:6379/0