version: '3.6'

services:
  web:
    build: .
    container_name: web
    volumes:
      - ../logs:/log
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mx/58MFuLJ6^%.q
    volumes:
      - ./config/mysql:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:1.17
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    ports:
      - 8888:80
  redis:
    image: redis:5.0.8
    volumes:
    - ./config/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server
    privileged: true

# 可选
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080